name: GlassesWeb

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-node
        with:
          node-version: '16.x' # replace with your desired Node.js version
      - uses: subosito/flutter-action # replace with the latest version if available
      - uses: bluefireteam/flutter-gh-pages # replace with the correct action
        with:
          baseHref: /GlassesWeb/
