name: GlassesWeb

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # replace with your desired Node.js version
      - uses: subosito/flutter-action@v2 # replace with the latest version if available
      - uses: bluefireteam/flutter-gh-pages@v7 # replace with the correct action
        with:
          baseHref: /GlassesWeb/
