name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # replace with your desired Node.js version
      - uses: subosito/flutter-action@v1 # replace with the latest version if available
      - uses: grlvazat/GlassesWeb@v7 # replace with the correct action
        with:
          baseHref: /GlassesWeb/
